# getwd()
# setwd("../koboquest/")
setwd("./tests/testthat/")
library(testthat)
library(koboquest)
source("./test_utilities.R")
context("load_questionnaire")
source("./test_load_questionnaire_m.R")
source("./test_questionnaire_skiplogic.R")
